/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ProoflyRegistry {
  export type ProofStruct = {
    id: BigNumberish;
    owner: AddressLike;
    contentHash: BytesLike;
    analysisHash: BytesLike;
    timestamp: BigNumberish;
    metadataURI: string;
    agentType: string;
  };

  export type ProofStructOutput = [
    id: bigint,
    owner: string,
    contentHash: string,
    analysisHash: string,
    timestamp: bigint,
    metadataURI: string,
    agentType: string
  ] & {
    id: bigint;
    owner: string;
    contentHash: string;
    analysisHash: string;
    timestamp: bigint;
    metadataURI: string;
    agentType: string;
  };
}

export interface ProoflyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProof"
      | "getProofByHash"
      | "getProofsByOwner"
      | "hashToProofIds"
      | "ownerProofs"
      | "proofCount"
      | "proofs"
      | "registerProof"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashToProofIds",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerProofs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proofCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proofs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProof",
    values: [BytesLike, BytesLike, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProofByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProofsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashToProofIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proofCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProof",
    data: BytesLike
  ): Result;
}

export namespace ProofRegisteredEvent {
  export type InputTuple = [
    proofId: BigNumberish,
    owner: AddressLike,
    contentHash: BytesLike,
    analysisHash: BytesLike,
    timestamp: BigNumberish,
    agentType: string
  ];
  export type OutputTuple = [
    proofId: bigint,
    owner: string,
    contentHash: string,
    analysisHash: string,
    timestamp: bigint,
    agentType: string
  ];
  export interface OutputObject {
    proofId: bigint;
    owner: string;
    contentHash: string;
    analysisHash: string;
    timestamp: bigint;
    agentType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProoflyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProoflyRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProoflyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProof: TypedContractMethod<
    [proofId: BigNumberish],
    [ProoflyRegistry.ProofStructOutput],
    "view"
  >;

  getProofByHash: TypedContractMethod<
    [contentHash: BytesLike],
    [bigint[]],
    "view"
  >;

  getProofsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  hashToProofIds: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  ownerProofs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  proofCount: TypedContractMethod<[], [bigint], "view">;

  proofs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, string, string] & {
        id: bigint;
        owner: string;
        contentHash: string;
        analysisHash: string;
        timestamp: bigint;
        metadataURI: string;
        agentType: string;
      }
    ],
    "view"
  >;

  registerProof: TypedContractMethod<
    [
      contentHash: BytesLike,
      analysisHash: BytesLike,
      metadataURI: string,
      agentType: string
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [proofId: BigNumberish],
    [ProoflyRegistry.ProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofByHash"
  ): TypedContractMethod<[contentHash: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProofsByOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hashToProofIds"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerProofs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, string, string] & {
        id: bigint;
        owner: string;
        contentHash: string;
        analysisHash: string;
        timestamp: bigint;
        metadataURI: string;
        agentType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProof"
  ): TypedContractMethod<
    [
      contentHash: BytesLike,
      analysisHash: BytesLike,
      metadataURI: string,
      agentType: string
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ProofRegistered"
  ): TypedContractEvent<
    ProofRegisteredEvent.InputTuple,
    ProofRegisteredEvent.OutputTuple,
    ProofRegisteredEvent.OutputObject
  >;

  filters: {
    "ProofRegistered(uint256,address,bytes32,bytes32,uint256,string)": TypedContractEvent<
      ProofRegisteredEvent.InputTuple,
      ProofRegisteredEvent.OutputTuple,
      ProofRegisteredEvent.OutputObject
    >;
    ProofRegistered: TypedContractEvent<
      ProofRegisteredEvent.InputTuple,
      ProofRegisteredEvent.OutputTuple,
      ProofRegisteredEvent.OutputObject
    >;
  };
}
